{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "31100c5e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "============================================================\n",
      "🌐 Overall Facebook Posts Summary\n",
      "============================================================\n",
      "\n",
      "📊 Numeric Summary:\n",
      "shape: (9, 41)\n",
      "┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐\n",
      "│ statistic ┆ Likes     ┆ Comments  ┆ Shares    ┆ … ┆ incivilit ┆ scam_illu ┆ freefair_ ┆ fraud_il │\n",
      "│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ y_illumin ┆ minating  ┆ illuminat ┆ luminati │\n",
      "│ str       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ ating     ┆ ---       ┆ ing       ┆ ng       │\n",
      "│           ┆           ┆           ┆           ┆   ┆ ---       ┆ f64       ┆ ---       ┆ ---      │\n",
      "│           ┆           ┆           ┆           ┆   ┆ f64       ┆           ┆ f64       ┆ f64      │\n",
      "╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡\n",
      "│ count     ┆ 19009.0   ┆ 19009.0   ┆ 19009.0   ┆ … ┆ 19009.0   ┆ 18060.0   ┆ 19009.0   ┆ 19009.0  │\n",
      "│ null_coun ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 949.0     ┆ 0.0       ┆ 0.0      │\n",
      "│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │\n",
      "│ mean      ┆ 2377.6954 ┆ 901.58319 ┆ 320.53895 ┆ … ┆ 0.127887  ┆ 0.02021   ┆ 0.002841  ┆ 0.008627 │\n",
      "│           ┆ 07        ┆ 7         ┆ 5         ┆   ┆           ┆           ┆           ┆          │\n",
      "│ std       ┆ 11253.469 ┆ 3681.9800 ┆ 1722.1598 ┆ … ┆ 0.333972  ┆ 0.140723  ┆ 0.053224  ┆ 0.092485 │\n",
      "│           ┆ 669       ┆ 96        ┆ 79        ┆   ┆           ┆           ┆           ┆          │\n",
      "│ min       ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │\n",
      "│ 25%       ┆ 31.0      ┆ 8.0       ┆ 3.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │\n",
      "│ 50%       ┆ 139.0     ┆ 48.0      ┆ 21.0      ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │\n",
      "│ 75%       ┆ 738.0     ┆ 354.0     ┆ 102.0     ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │\n",
      "│ max       ┆ 351979.0  ┆ 93872.0   ┆ 76150.0   ┆ … ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ 1.0      │\n",
      "└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘\n",
      "\n",
      "📝 Categorical Summary:\n",
      "- Facebook_Id:\n",
      "    Unique values : 21\n",
      "    Most frequent : 'fedbfaab19b5112a6889b862314ca9d3a626b22df7f959db3d9b1c4c54e69948' (643 times)'\n",
      "- post_id:\n",
      "    Unique values : 19009\n",
      "    Most frequent : '3b45de24b44c7d165a67384c9fd5954806f7e9a1060269a878389114c66f4bec' (1 times)'\n",
      "- Page Category:\n",
      "    Unique values : 7\n",
      "    Most frequent : 'YOUTH_ORGANIZATION' (1 times)'\n",
      "- Page Admin Top Country:\n",
      "    Unique values : 2\n",
      "    Most frequent : 'US' (16280 times)'\n",
      "- Post Created:\n",
      "    Unique values : 18951\n",
      "    Most frequent : '2024-02-05 12:30:15 EST' (1 times)'\n",
      "- Post Created Date:\n",
      "    Unique values : 425\n",
      "    Most frequent : '2024-01-15' (96 times)'\n",
      "- Post Created Time:\n",
      "    Unique values : 16102\n",
      "    Most frequent : '09:33:44' (2 times)'\n",
      "- Type:\n",
      "    Unique values : 10\n",
      "    Most frequent : 'Video' (64 times)'\n",
      "- Total Interactions:\n",
      "    Unique values : 5665\n",
      "    Most frequent : '2516' (1 times)'\n",
      "- Video Share Status:\n",
      "    Unique values : 4\n",
      "    Most frequent : 'crosspost' (72 times)'\n",
      "- Is Video Owner?:\n",
      "    Unique values : 4\n",
      "    Most frequent : 'No' (83 times)'\n",
      "- Video Length:\n",
      "    Unique values : 775\n",
      "    Most frequent : '00:08:14' (4 times)'\n",
      "- Sponsor Id:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (19009 times)'\n",
      "- Sponsor Name:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (19009 times)'\n",
      "- Sponsor Category:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (19009 times)'\n",
      "- illuminating_scored_messageelection_integrity_Truth_illuminating:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (19009 times)'\n",
      "\n",
      "\n",
      "============================================================\n",
      "📁 Grouped by Facebook_Id = bfe51c6ac2cab17ba5c85883e76f61398031ed57e4cf62d19fd483548ebb904b\n",
      "============================================================\n",
      "\n",
      "📊 Numeric Summary:\n",
      "shape: (9, 41)\n",
      "┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐\n",
      "│ statistic ┆ Likes     ┆ Comments  ┆ Shares    ┆ … ┆ incivilit ┆ scam_illu ┆ freefair_ ┆ fraud_il │\n",
      "│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ y_illumin ┆ minating  ┆ illuminat ┆ luminati │\n",
      "│ str       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ ating     ┆ ---       ┆ ing       ┆ ng       │\n",
      "│           ┆           ┆           ┆           ┆   ┆ ---       ┆ f64       ┆ ---       ┆ ---      │\n",
      "│           ┆           ┆           ┆           ┆   ┆ f64       ┆           ┆ f64       ┆ f64      │\n",
      "╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡\n",
      "│ count     ┆ 1431.0    ┆ 1431.0    ┆ 1431.0    ┆ … ┆ 1431.0    ┆ 1431.0    ┆ 1431.0    ┆ 1431.0   │\n",
      "│ null_coun ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │\n",
      "│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │\n",
      "│ mean      ┆ 262.42278 ┆ 81.204752 ┆ 56.387841 ┆ … ┆ 0.125087  ┆ 0.088749  ┆ 0.001398  ┆ 0.001398 │\n",
      "│           ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │\n",
      "│ std       ┆ 580.74604 ┆ 190.81693 ┆ 107.28707 ┆ … ┆ 0.330934  ┆ 0.284481  ┆ 0.037372  ┆ 0.037372 │\n",
      "│           ┆ 7         ┆ 5         ┆ 2         ┆   ┆           ┆           ┆           ┆          │\n",
      "│ min       ┆ 2.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │\n",
      "│ 25%       ┆ 61.0      ┆ 9.0       ┆ 15.0      ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │\n",
      "│ 50%       ┆ 100.0     ┆ 24.0      ┆ 31.0      ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │\n",
      "│ 75%       ┆ 217.0     ┆ 71.0      ┆ 59.0      ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │\n",
      "│ max       ┆ 7495.0    ┆ 2937.0    ┆ 2223.0    ┆ … ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ 1.0      │\n",
      "└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘\n",
      "\n",
      "📝 Categorical Summary:\n",
      "- Facebook_Id:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'bfe51c6ac2cab17ba5c85883e76f61398031ed57e4cf62d19fd483548ebb904b' (1431 times)'\n",
      "- post_id:\n",
      "    Unique values : 1431\n",
      "    Most frequent : 'f8d0120219e655a2019bfc8d6eae508ee6d9d7eb4a0b8c465e30efd74d490155' (1 times)'\n",
      "- Page Category:\n",
      "    Unique values : 2\n",
      "    Most frequent : 'PERSON' (1283 times)'\n",
      "- Page Admin Top Country:\n",
      "    Unique values : 2\n",
      "    Most frequent : 'None' (148 times)'\n",
      "- Post Created:\n",
      "    Unique values : 1425\n",
      "    Most frequent : '2024-09-27T05:29:02.000Z' (1 times)'\n",
      "- Post Created Date:\n",
      "    Unique values : 359\n",
      "    Most frequent : '2024-11-03' (3 times)'\n",
      "- Post Created Time:\n",
      "    Unique values : 1415\n",
      "    Most frequent : '20:30:40' (1 times)'\n",
      "- Type:\n",
      "    Unique values : 9\n",
      "    Most frequent : 'Link' (130 times)'\n",
      "- Total Interactions:\n",
      "    Unique values : 701\n",
      "    Most frequent : '1,499' (1 times)'\n",
      "- Video Share Status:\n",
      "    Unique values : 4\n",
      "    Most frequent : 'owned' (427 times)'\n",
      "- Is Video Owner?:\n",
      "    Unique values : 4\n",
      "    Most frequent : 'None' (148 times)'\n",
      "- Video Length:\n",
      "    Unique values : 231\n",
      "    Most frequent : '00:03:25' (3 times)'\n",
      "- Sponsor Id:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (1431 times)'\n",
      "- Sponsor Name:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (1431 times)'\n",
      "- Sponsor Category:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (1431 times)'\n",
      "- illuminating_scored_messageelection_integrity_Truth_illuminating:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (1431 times)'\n",
      "\n",
      "\n",
      "============================================================\n",
      "📁 Grouped by Facebook_Id = ac24f31c4d4b3d5555065fa9558bdca4ab4b5e1379922875ae9e6e32f1d46d25\n",
      "============================================================\n",
      "\n",
      "📊 Numeric Summary:\n",
      "shape: (9, 41)\n",
      "┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐\n",
      "│ statistic ┆ Likes     ┆ Comments  ┆ Shares    ┆ … ┆ incivilit ┆ scam_illu ┆ freefair_ ┆ fraud_il │\n",
      "│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ y_illumin ┆ minating  ┆ illuminat ┆ luminati │\n",
      "│ str       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ ating     ┆ ---       ┆ ing       ┆ ng       │\n",
      "│           ┆           ┆           ┆           ┆   ┆ ---       ┆ f64       ┆ ---       ┆ ---      │\n",
      "│           ┆           ┆           ┆           ┆   ┆ f64       ┆           ┆ f64       ┆ f64      │\n",
      "╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡\n",
      "│ count     ┆ 1231.0    ┆ 1231.0    ┆ 1231.0    ┆ … ┆ 1231.0    ┆ 1231.0    ┆ 1231.0    ┆ 1231.0   │\n",
      "│ null_coun ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │\n",
      "│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │\n",
      "│ mean      ┆ 5042.9228 ┆ 1842.9748 ┆ 600.94719 ┆ … ┆ 0.109667  ┆ 0.001625  ┆ 0.003249  ┆ 0.0      │\n",
      "│           ┆ 27        ┆ 17        ┆ 7         ┆   ┆           ┆           ┆           ┆          │\n",
      "│ std       ┆ 10170.526 ┆ 2743.8483 ┆ 1324.9811 ┆ … ┆ 0.312601  ┆ 0.040291  ┆ 0.056934  ┆ 0.0      │\n",
      "│           ┆ 942       ┆ 97        ┆ 08        ┆   ┆           ┆           ┆           ┆          │\n",
      "│ min       ┆ 52.0      ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │\n",
      "│ 25%       ┆ 762.0     ┆ 436.0     ┆ 94.0      ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │\n",
      "│ 50%       ┆ 1427.0    ┆ 729.0     ┆ 182.0     ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │\n",
      "│ 75%       ┆ 5081.0    ┆ 2081.0    ┆ 550.0     ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │\n",
      "│ max       ┆ 121951.0  ┆ 28113.0   ┆ 21291.0   ┆ … ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ 0.0      │\n",
      "└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘\n",
      "\n",
      "📝 Categorical Summary:\n",
      "- Facebook_Id:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'ac24f31c4d4b3d5555065fa9558bdca4ab4b5e1379922875ae9e6e32f1d46d25' (1231 times)'\n",
      "- post_id:\n",
      "    Unique values : 1231\n",
      "    Most frequent : '7d97ef7736d6d80c053e0d35b061df654acc56d2323cc8c3bd0fe9410e78e694' (1 times)'\n",
      "- Page Category:\n",
      "    Unique values : 2\n",
      "    Most frequent : 'POLITICIAN' (867 times)'\n",
      "- Page Admin Top Country:\n",
      "    Unique values : 2\n",
      "    Most frequent : 'US' (867 times)'\n",
      "- Post Created:\n",
      "    Unique values : 1231\n",
      "    Most frequent : '2024-07-23 19:43:00 EDT' (1 times)'\n",
      "- Post Created Date:\n",
      "    Unique values : 340\n",
      "    Most frequent : '2023-12-04' (1 times)'\n",
      "- Post Created Time:\n",
      "    Unique values : 1134\n",
      "    Most frequent : '17:39:10' (1 times)'\n",
      "- Type:\n",
      "    Unique values : 7\n",
      "    Most frequent : 'None' (364 times)'\n",
      "- Total Interactions:\n",
      "    Unique values : 1150\n",
      "    Most frequent : '2,275' (1 times)'\n",
      "- Video Share Status:\n",
      "    Unique values : 4\n",
      "    Most frequent : 'crosspost' (2 times)'\n",
      "- Is Video Owner?:\n",
      "    Unique values : 4\n",
      "    Most frequent : 'None' (364 times)'\n",
      "- Video Length:\n",
      "    Unique values : 107\n",
      "    Most frequent : '00:01:38' (1 times)'\n",
      "- Sponsor Id:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (1231 times)'\n",
      "- Sponsor Name:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (1231 times)'\n",
      "- Sponsor Category:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (1231 times)'\n",
      "- illuminating_scored_messageelection_integrity_Truth_illuminating:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (1231 times)'\n",
      "\n",
      "\n",
      "============================================================\n",
      "📁 Grouped by Facebook_Id = 278df0e37b61bf8a5a6374873b38faddd50fffea73eaeb55c3c6240f79d1ba9f\n",
      "============================================================\n",
      "\n",
      "📊 Numeric Summary:\n",
      "shape: (9, 41)\n",
      "┌────────────┬───────────┬──────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐\n",
      "│ statistic  ┆ Likes     ┆ Comments ┆ Shares   ┆ … ┆ incivilit ┆ scam_illu ┆ freefair_ ┆ fraud_ill │\n",
      "│ ---        ┆ ---       ┆ ---      ┆ ---      ┆   ┆ y_illumin ┆ minating  ┆ illuminat ┆ uminating │\n",
      "│ str        ┆ f64       ┆ f64      ┆ f64      ┆   ┆ ating     ┆ ---       ┆ ing       ┆ ---       │\n",
      "│            ┆           ┆          ┆          ┆   ┆ ---       ┆ f64       ┆ ---       ┆ f64       │\n",
      "│            ┆           ┆          ┆          ┆   ┆ f64       ┆           ┆ f64       ┆           │\n",
      "╞════════════╪═══════════╪══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡\n",
      "│ count      ┆ 23.0      ┆ 23.0     ┆ 23.0     ┆ … ┆ 23.0      ┆ 23.0      ┆ 23.0      ┆ 23.0      │\n",
      "│ null_count ┆ 0.0       ┆ 0.0      ┆ 0.0      ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │\n",
      "│ mean       ┆ 6.26087   ┆ 3.826087 ┆ 0.478261 ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │\n",
      "│ std        ┆ 16.057333 ┆ 9.679651 ┆ 0.790257 ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │\n",
      "│ min        ┆ 0.0       ┆ 0.0      ┆ 0.0      ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │\n",
      "│ 25%        ┆ 1.0       ┆ 0.0      ┆ 0.0      ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │\n",
      "│ 50%        ┆ 2.0       ┆ 0.0      ┆ 0.0      ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │\n",
      "│ 75%        ┆ 4.0       ┆ 2.0      ┆ 1.0      ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │\n",
      "│ max        ┆ 78.0      ┆ 43.0     ┆ 3.0      ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │\n",
      "└────────────┴───────────┴──────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘\n",
      "\n",
      "📝 Categorical Summary:\n",
      "- Facebook_Id:\n",
      "    Unique values : 1\n",
      "    Most frequent : '278df0e37b61bf8a5a6374873b38faddd50fffea73eaeb55c3c6240f79d1ba9f' (23 times)'\n",
      "- post_id:\n",
      "    Unique values : 23\n",
      "    Most frequent : 'eb95d4e297c8addae91d7a185d4909bdf7f90b714d31786bade75bcb987c07b6' (1 times)'\n",
      "- Page Category:\n",
      "    Unique values : 3\n",
      "    Most frequent : 'POLITICAL_CANDIDATE' (15 times)'\n",
      "- Page Admin Top Country:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (23 times)'\n",
      "- Post Created:\n",
      "    Unique values : 23\n",
      "    Most frequent : '2024-04-17 10:14:29 EDT' (1 times)'\n",
      "- Post Created Date:\n",
      "    Unique values : 17\n",
      "    Most frequent : '2024-06-10' (1 times)'\n",
      "- Post Created Time:\n",
      "    Unique values : 23\n",
      "    Most frequent : '12:59:20' (1 times)'\n",
      "- Type:\n",
      "    Unique values : 4\n",
      "    Most frequent : 'Native Video' (4 times)'\n",
      "- Total Interactions:\n",
      "    Unique values : 12\n",
      "    Most frequent : '1' (2 times)'\n",
      "- Video Share Status:\n",
      "    Unique values : 3\n",
      "    Most frequent : 'share' (3 times)'\n",
      "- Is Video Owner?:\n",
      "    Unique values : 3\n",
      "    Most frequent : 'Yes' (1 times)'\n",
      "- Video Length:\n",
      "    Unique values : 5\n",
      "    Most frequent : '00:00:38' (1 times)'\n",
      "- Sponsor Id:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (23 times)'\n",
      "- Sponsor Name:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (23 times)'\n",
      "- Sponsor Category:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (23 times)'\n",
      "- illuminating_scored_messageelection_integrity_Truth_illuminating:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (23 times)'\n",
      "\n",
      "\n",
      "============================================================\n",
      "📁 Grouped by Facebook_Id = d6008f090fcb5df7263efe969d3fc268e0ec1f6d75c8ff692b2eeacc9c48b309\n",
      "============================================================\n",
      "\n",
      "📊 Numeric Summary:\n",
      "shape: (9, 41)\n",
      "┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐\n",
      "│ statistic ┆ Likes     ┆ Comments  ┆ Shares    ┆ … ┆ incivilit ┆ scam_illu ┆ freefair_ ┆ fraud_il │\n",
      "│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ y_illumin ┆ minating  ┆ illuminat ┆ luminati │\n",
      "│ str       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ ating     ┆ ---       ┆ ing       ┆ ng       │\n",
      "│           ┆           ┆           ┆           ┆   ┆ ---       ┆ f64       ┆ ---       ┆ ---      │\n",
      "│           ┆           ┆           ┆           ┆   ┆ f64       ┆           ┆ f64       ┆ f64      │\n",
      "╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡\n",
      "│ count     ┆ 929.0     ┆ 929.0     ┆ 929.0     ┆ … ┆ 929.0     ┆ 929.0     ┆ 929.0     ┆ 929.0    │\n",
      "│ null_coun ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │\n",
      "│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │\n",
      "│ mean      ┆ 5086.6910 ┆ 3711.9569 ┆ 975.35306 ┆ … ┆ 0.142088  ┆ 0.005382  ┆ 0.005382  ┆ 0.001076 │\n",
      "│           ┆ 66        ┆ 43        ┆ 8         ┆   ┆           ┆           ┆           ┆          │\n",
      "│ std       ┆ 7142.5324 ┆ 2880.3266 ┆ 3151.8859 ┆ … ┆ 0.349329  ┆ 0.073205  ┆ 0.073205  ┆ 0.032809 │\n",
      "│           ┆ 39        ┆ 94        ┆ 29        ┆   ┆           ┆           ┆           ┆          │\n",
      "│ min       ┆ 377.0     ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │\n",
      "│ 25%       ┆ 2190.0    ┆ 2227.0    ┆ 331.0     ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │\n",
      "│ 50%       ┆ 3250.0    ┆ 3068.0    ┆ 533.0     ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │\n",
      "│ 75%       ┆ 5268.0    ┆ 4388.0    ┆ 957.0     ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │\n",
      "│ max       ┆ 97979.0   ┆ 51060.0   ┆ 76150.0   ┆ … ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ 1.0      │\n",
      "└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘\n",
      "\n",
      "📝 Categorical Summary:\n",
      "- Facebook_Id:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'd6008f090fcb5df7263efe969d3fc268e0ec1f6d75c8ff692b2eeacc9c48b309' (929 times)'\n",
      "- post_id:\n",
      "    Unique values : 929\n",
      "    Most frequent : '7e812e5f88140b60a4b976c10f9bbe93a3654ec12066ae9b7b00bcc744641fab' (1 times)'\n",
      "- Page Category:\n",
      "    Unique values : 2\n",
      "    Most frequent : 'None' (82 times)'\n",
      "- Page Admin Top Country:\n",
      "    Unique values : 2\n",
      "    Most frequent : 'None' (82 times)'\n",
      "- Post Created:\n",
      "    Unique values : 928\n",
      "    Most frequent : '2024-01-05 15:19:57 EST' (1 times)'\n",
      "- Post Created Date:\n",
      "    Unique values : 311\n",
      "    Most frequent : '2023-09-28' (4 times)'\n",
      "- Post Created Time:\n",
      "    Unique values : 839\n",
      "    Most frequent : '09:30:04' (1 times)'\n",
      "- Type:\n",
      "    Unique values : 7\n",
      "    Most frequent : 'None' (82 times)'\n",
      "- Total Interactions:\n",
      "    Unique values : 912\n",
      "    Most frequent : '2,993' (1 times)'\n",
      "- Video Share Status:\n",
      "    Unique values : 4\n",
      "    Most frequent : 'crosspost' (4 times)'\n",
      "- Is Video Owner?:\n",
      "    Unique values : 4\n",
      "    Most frequent : '-' (584 times)'\n",
      "- Video Length:\n",
      "    Unique values : 94\n",
      "    Most frequent : '00:00:12' (6 times)'\n",
      "- Sponsor Id:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (929 times)'\n",
      "- Sponsor Name:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (929 times)'\n",
      "- Sponsor Category:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (929 times)'\n",
      "- illuminating_scored_messageelection_integrity_Truth_illuminating:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (929 times)'\n",
      "\n",
      "\n",
      "============================================================\n",
      "📁 Grouped by Facebook_Id = fedbfaab19b5112a6889b862314ca9d3a626b22df7f959db3d9b1c4c54e69948\n",
      "============================================================\n",
      "\n",
      "📊 Numeric Summary:\n",
      "shape: (9, 41)\n",
      "┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐\n",
      "│ statistic ┆ Likes     ┆ Comments  ┆ Shares    ┆ … ┆ incivilit ┆ scam_illu ┆ freefair_ ┆ fraud_il │\n",
      "│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ y_illumin ┆ minating  ┆ illuminat ┆ luminati │\n",
      "│ str       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ ating     ┆ ---       ┆ ing       ┆ ng       │\n",
      "│           ┆           ┆           ┆           ┆   ┆ ---       ┆ f64       ┆ ---       ┆ ---      │\n",
      "│           ┆           ┆           ┆           ┆   ┆ f64       ┆           ┆ f64       ┆ f64      │\n",
      "╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡\n",
      "│ count     ┆ 643.0     ┆ 643.0     ┆ 643.0     ┆ … ┆ 643.0     ┆ 643.0     ┆ 643.0     ┆ 643.0    │\n",
      "│ null_coun ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │\n",
      "│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │\n",
      "│ mean      ┆ 3246.5412 ┆ 647.87402 ┆ 830.56609 ┆ … ┆ 0.157076  ┆ 0.004666  ┆ 0.0       ┆ 0.001555 │\n",
      "│           ┆ 13        ┆ 8         ┆ 6         ┆   ┆           ┆           ┆           ┆          │\n",
      "│ std       ┆ 6773.2615 ┆ 1070.1883 ┆ 1661.6466 ┆ … ┆ 0.364156  ┆ 0.068199  ┆ 0.0       ┆ 0.039436 │\n",
      "│           ┆ 92        ┆ 88        ┆ 03        ┆   ┆           ┆           ┆           ┆          │\n",
      "│ min       ┆ 80.0      ┆ 7.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │\n",
      "│ 25%       ┆ 794.0     ┆ 206.0     ┆ 199.0     ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │\n",
      "│ 50%       ┆ 1320.0    ┆ 352.0     ┆ 378.0     ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │\n",
      "│ 75%       ┆ 2678.0    ┆ 571.0     ┆ 745.0     ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │\n",
      "│ max       ┆ 72898.0   ┆ 10688.0   ┆ 23031.0   ┆ … ┆ 1.0       ┆ 1.0       ┆ 0.0       ┆ 1.0      │\n",
      "└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘\n",
      "\n",
      "📝 Categorical Summary:\n",
      "- Facebook_Id:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'fedbfaab19b5112a6889b862314ca9d3a626b22df7f959db3d9b1c4c54e69948' (643 times)'\n",
      "- post_id:\n",
      "    Unique values : 643\n",
      "    Most frequent : 'fa305a6f358c263a0c6904e0f6bc74b20645054ebe5fd9b9d98ab532a84b0453' (1 times)'\n",
      "- Page Category:\n",
      "    Unique values : 2\n",
      "    Most frequent : 'POLITICAL_CANDIDATE' (547 times)'\n",
      "- Page Admin Top Country:\n",
      "    Unique values : 2\n",
      "    Most frequent : 'None' (96 times)'\n",
      "- Post Created:\n",
      "    Unique values : 643\n",
      "    Most frequent : '2023-09-08 15:00:02 EDT' (1 times)'\n",
      "- Post Created Date:\n",
      "    Unique values : 295\n",
      "    Most frequent : '2024-04-20' (3 times)'\n",
      "- Post Created Time:\n",
      "    Unique values : 641\n",
      "    Most frequent : '19:03:32' (1 times)'\n",
      "- Type:\n",
      "    Unique values : 8\n",
      "    Most frequent : 'Live Video Scheduled' (10 times)'\n",
      "- Total Interactions:\n",
      "    Unique values : 611\n",
      "    Most frequent : '2,572' (1 times)'\n",
      "- Video Share Status:\n",
      "    Unique values : 2\n",
      "    Most frequent : 'owned' (328 times)'\n",
      "- Is Video Owner?:\n",
      "    Unique values : 3\n",
      "    Most frequent : 'None' (96 times)'\n",
      "- Video Length:\n",
      "    Unique values : 199\n",
      "    Most frequent : '00:04:39' (1 times)'\n",
      "- Sponsor Id:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (643 times)'\n",
      "- Sponsor Name:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (643 times)'\n",
      "- Sponsor Category:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (643 times)'\n",
      "- illuminating_scored_messageelection_integrity_Truth_illuminating:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (643 times)'\n",
      "\n",
      "\n",
      "============================================================\n",
      "🔗 Grouped by Facebook_Id = ee4bad47ee7b6d5da4b19f72dfc6df401cb36563474277cbf66624e2151cc84d, post_id = 314d895da0a05af86e4af4f8eb973e328ae7189c25f727db7b4a824310f77f46\n",
      "============================================================\n",
      "\n",
      "📊 Numeric Summary:\n",
      "shape: (9, 41)\n",
      "┌────────────┬───────┬──────────┬────────┬───┬─────────────┬─────────────┬────────────┬────────────┐\n",
      "│ statistic  ┆ Likes ┆ Comments ┆ Shares ┆ … ┆ incivility_ ┆ scam_illumi ┆ freefair_i ┆ fraud_illu │\n",
      "│ ---        ┆ ---   ┆ ---      ┆ ---    ┆   ┆ illuminatin ┆ nating      ┆ lluminatin ┆ minating   │\n",
      "│ str        ┆ f64   ┆ f64      ┆ f64    ┆   ┆ g           ┆ ---         ┆ g          ┆ ---        │\n",
      "│            ┆       ┆          ┆        ┆   ┆ ---         ┆ f64         ┆ ---        ┆ f64        │\n",
      "│            ┆       ┆          ┆        ┆   ┆ f64         ┆             ┆ f64        ┆            │\n",
      "╞════════════╪═══════╪══════════╪════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡\n",
      "│ count      ┆ 1.0   ┆ 1.0      ┆ 1.0    ┆ … ┆ 1.0         ┆ 1.0         ┆ 1.0        ┆ 1.0        │\n",
      "│ null_count ┆ 0.0   ┆ 0.0      ┆ 0.0    ┆ … ┆ 0.0         ┆ 0.0         ┆ 0.0        ┆ 0.0        │\n",
      "│ mean       ┆ 23.0  ┆ 4.0      ┆ 7.0    ┆ … ┆ 0.0         ┆ 0.0         ┆ 0.0        ┆ 0.0        │\n",
      "│ std        ┆ null  ┆ null     ┆ null   ┆ … ┆ null        ┆ null        ┆ null       ┆ null       │\n",
      "│ min        ┆ 23.0  ┆ 4.0      ┆ 7.0    ┆ … ┆ 0.0         ┆ 0.0         ┆ 0.0        ┆ 0.0        │\n",
      "│ 25%        ┆ 23.0  ┆ 4.0      ┆ 7.0    ┆ … ┆ 0.0         ┆ 0.0         ┆ 0.0        ┆ 0.0        │\n",
      "│ 50%        ┆ 23.0  ┆ 4.0      ┆ 7.0    ┆ … ┆ 0.0         ┆ 0.0         ┆ 0.0        ┆ 0.0        │\n",
      "│ 75%        ┆ 23.0  ┆ 4.0      ┆ 7.0    ┆ … ┆ 0.0         ┆ 0.0         ┆ 0.0        ┆ 0.0        │\n",
      "│ max        ┆ 23.0  ┆ 4.0      ┆ 7.0    ┆ … ┆ 0.0         ┆ 0.0         ┆ 0.0        ┆ 0.0        │\n",
      "└────────────┴───────┴──────────┴────────┴───┴─────────────┴─────────────┴────────────┴────────────┘\n",
      "\n",
      "📝 Categorical Summary:\n",
      "- Facebook_Id:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'ee4bad47ee7b6d5da4b19f72dfc6df401cb36563474277cbf66624e2151cc84d' (1 times)'\n",
      "- post_id:\n",
      "    Unique values : 1\n",
      "    Most frequent : '314d895da0a05af86e4af4f8eb973e328ae7189c25f727db7b4a824310f77f46' (1 times)'\n",
      "- Page Category:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'POLITICAL_CANDIDATE' (1 times)'\n",
      "- Page Admin Top Country:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (1 times)'\n",
      "- Post Created:\n",
      "    Unique values : 1\n",
      "    Most frequent : '2024-02-07 10:26:43 EST' (1 times)'\n",
      "- Post Created Date:\n",
      "    Unique values : 1\n",
      "    Most frequent : '2024-02-07' (1 times)'\n",
      "- Post Created Time:\n",
      "    Unique values : 1\n",
      "    Most frequent : '10:26:43' (1 times)'\n",
      "- Type:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'Native Video' (1 times)'\n",
      "- Total Interactions:\n",
      "    Unique values : 1\n",
      "    Most frequent : '35' (1 times)'\n",
      "- Video Share Status:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'owned' (1 times)'\n",
      "- Is Video Owner?:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'Yes' (1 times)'\n",
      "- Video Length:\n",
      "    Unique values : 1\n",
      "    Most frequent : '00:00:10' (1 times)'\n",
      "- Sponsor Id:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (1 times)'\n",
      "- Sponsor Name:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (1 times)'\n",
      "- Sponsor Category:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (1 times)'\n",
      "- illuminating_scored_messageelection_integrity_Truth_illuminating:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (1 times)'\n",
      "\n",
      "\n",
      "============================================================\n",
      "🔗 Grouped by Facebook_Id = 32fc18da91029ff09bf74fe9887eace6b5d2145809d583f696e344530508b064, post_id = 058e7a7e5b45806768292cde9496d60534325879bcf1d8fb098b643e670b8e05\n",
      "============================================================\n",
      "\n",
      "📊 Numeric Summary:\n",
      "shape: (9, 41)\n",
      "┌────────────┬───────┬──────────┬────────┬───┬─────────────┬─────────────┬────────────┬────────────┐\n",
      "│ statistic  ┆ Likes ┆ Comments ┆ Shares ┆ … ┆ incivility_ ┆ scam_illumi ┆ freefair_i ┆ fraud_illu │\n",
      "│ ---        ┆ ---   ┆ ---      ┆ ---    ┆   ┆ illuminatin ┆ nating      ┆ lluminatin ┆ minating   │\n",
      "│ str        ┆ f64   ┆ f64      ┆ f64    ┆   ┆ g           ┆ ---         ┆ g          ┆ ---        │\n",
      "│            ┆       ┆          ┆        ┆   ┆ ---         ┆ f64         ┆ ---        ┆ f64        │\n",
      "│            ┆       ┆          ┆        ┆   ┆ f64         ┆             ┆ f64        ┆            │\n",
      "╞════════════╪═══════╪══════════╪════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡\n",
      "│ count      ┆ 1.0   ┆ 1.0      ┆ 1.0    ┆ … ┆ 1.0         ┆ 1.0         ┆ 1.0        ┆ 1.0        │\n",
      "│ null_count ┆ 0.0   ┆ 0.0      ┆ 0.0    ┆ … ┆ 0.0         ┆ 0.0         ┆ 0.0        ┆ 0.0        │\n",
      "│ mean       ┆ 11.0  ┆ 0.0      ┆ 2.0    ┆ … ┆ 0.0         ┆ 0.0         ┆ 0.0        ┆ 0.0        │\n",
      "│ std        ┆ null  ┆ null     ┆ null   ┆ … ┆ null        ┆ null        ┆ null       ┆ null       │\n",
      "│ min        ┆ 11.0  ┆ 0.0      ┆ 2.0    ┆ … ┆ 0.0         ┆ 0.0         ┆ 0.0        ┆ 0.0        │\n",
      "│ 25%        ┆ 11.0  ┆ 0.0      ┆ 2.0    ┆ … ┆ 0.0         ┆ 0.0         ┆ 0.0        ┆ 0.0        │\n",
      "│ 50%        ┆ 11.0  ┆ 0.0      ┆ 2.0    ┆ … ┆ 0.0         ┆ 0.0         ┆ 0.0        ┆ 0.0        │\n",
      "│ 75%        ┆ 11.0  ┆ 0.0      ┆ 2.0    ┆ … ┆ 0.0         ┆ 0.0         ┆ 0.0        ┆ 0.0        │\n",
      "│ max        ┆ 11.0  ┆ 0.0      ┆ 2.0    ┆ … ┆ 0.0         ┆ 0.0         ┆ 0.0        ┆ 0.0        │\n",
      "└────────────┴───────┴──────────┴────────┴───┴─────────────┴─────────────┴────────────┴────────────┘\n",
      "\n",
      "📝 Categorical Summary:\n",
      "- Facebook_Id:\n",
      "    Unique values : 1\n",
      "    Most frequent : '32fc18da91029ff09bf74fe9887eace6b5d2145809d583f696e344530508b064' (1 times)'\n",
      "- post_id:\n",
      "    Unique values : 1\n",
      "    Most frequent : '058e7a7e5b45806768292cde9496d60534325879bcf1d8fb098b643e670b8e05' (1 times)'\n",
      "- Page Category:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'PERSON' (1 times)'\n",
      "- Page Admin Top Country:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'US' (1 times)'\n",
      "- Post Created:\n",
      "    Unique values : 1\n",
      "    Most frequent : '2024-03-15 11:24:04 EDT' (1 times)'\n",
      "- Post Created Date:\n",
      "    Unique values : 1\n",
      "    Most frequent : '2024-03-15' (1 times)'\n",
      "- Post Created Time:\n",
      "    Unique values : 1\n",
      "    Most frequent : '11:24:04' (1 times)'\n",
      "- Type:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'Link' (1 times)'\n",
      "- Total Interactions:\n",
      "    Unique values : 1\n",
      "    Most frequent : '13' (1 times)'\n",
      "- Video Share Status:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (1 times)'\n",
      "- Is Video Owner?:\n",
      "    Unique values : 1\n",
      "    Most frequent : '-' (1 times)'\n",
      "- Video Length:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (1 times)'\n",
      "- Sponsor Id:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (1 times)'\n",
      "- Sponsor Name:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (1 times)'\n",
      "- Sponsor Category:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (1 times)'\n",
      "- illuminating_scored_messageelection_integrity_Truth_illuminating:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (1 times)'\n",
      "\n",
      "\n",
      "============================================================\n",
      "🔗 Grouped by Facebook_Id = b1daf9f2909abed80b7e02520dfd0bfdc22128e3b92c2aba8cb3b44a6bc42cbe, post_id = ce7afa4594f5488a71b97e0d2c504a42233e8395f7a29797be78c10779178d7b\n",
      "============================================================\n",
      "\n",
      "📊 Numeric Summary:\n",
      "shape: (9, 41)\n",
      "┌────────────┬───────┬──────────┬────────┬───┬─────────────┬─────────────┬────────────┬────────────┐\n",
      "│ statistic  ┆ Likes ┆ Comments ┆ Shares ┆ … ┆ incivility_ ┆ scam_illumi ┆ freefair_i ┆ fraud_illu │\n",
      "│ ---        ┆ ---   ┆ ---      ┆ ---    ┆   ┆ illuminatin ┆ nating      ┆ lluminatin ┆ minating   │\n",
      "│ str        ┆ f64   ┆ f64      ┆ f64    ┆   ┆ g           ┆ ---         ┆ g          ┆ ---        │\n",
      "│            ┆       ┆          ┆        ┆   ┆ ---         ┆ f64         ┆ ---        ┆ f64        │\n",
      "│            ┆       ┆          ┆        ┆   ┆ f64         ┆             ┆ f64        ┆            │\n",
      "╞════════════╪═══════╪══════════╪════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡\n",
      "│ count      ┆ 1.0   ┆ 1.0      ┆ 1.0    ┆ … ┆ 1.0         ┆ 1.0         ┆ 1.0        ┆ 1.0        │\n",
      "│ null_count ┆ 0.0   ┆ 0.0      ┆ 0.0    ┆ … ┆ 0.0         ┆ 0.0         ┆ 0.0        ┆ 0.0        │\n",
      "│ mean       ┆ 502.0 ┆ 560.0    ┆ 46.0   ┆ … ┆ 0.0         ┆ 0.0         ┆ 0.0        ┆ 0.0        │\n",
      "│ std        ┆ null  ┆ null     ┆ null   ┆ … ┆ null        ┆ null        ┆ null       ┆ null       │\n",
      "│ min        ┆ 502.0 ┆ 560.0    ┆ 46.0   ┆ … ┆ 0.0         ┆ 0.0         ┆ 0.0        ┆ 0.0        │\n",
      "│ 25%        ┆ 502.0 ┆ 560.0    ┆ 46.0   ┆ … ┆ 0.0         ┆ 0.0         ┆ 0.0        ┆ 0.0        │\n",
      "│ 50%        ┆ 502.0 ┆ 560.0    ┆ 46.0   ┆ … ┆ 0.0         ┆ 0.0         ┆ 0.0        ┆ 0.0        │\n",
      "│ 75%        ┆ 502.0 ┆ 560.0    ┆ 46.0   ┆ … ┆ 0.0         ┆ 0.0         ┆ 0.0        ┆ 0.0        │\n",
      "│ max        ┆ 502.0 ┆ 560.0    ┆ 46.0   ┆ … ┆ 0.0         ┆ 0.0         ┆ 0.0        ┆ 0.0        │\n",
      "└────────────┴───────┴──────────┴────────┴───┴─────────────┴─────────────┴────────────┴────────────┘\n",
      "\n",
      "📝 Categorical Summary:\n",
      "- Facebook_Id:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'b1daf9f2909abed80b7e02520dfd0bfdc22128e3b92c2aba8cb3b44a6bc42cbe' (1 times)'\n",
      "- post_id:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'ce7afa4594f5488a71b97e0d2c504a42233e8395f7a29797be78c10779178d7b' (1 times)'\n",
      "- Page Category:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'PERSON' (1 times)'\n",
      "- Page Admin Top Country:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'US' (1 times)'\n",
      "- Post Created:\n",
      "    Unique values : 1\n",
      "    Most frequent : '2023-11-03 13:20:50 EDT' (1 times)'\n",
      "- Post Created Date:\n",
      "    Unique values : 1\n",
      "    Most frequent : '2023-11-03' (1 times)'\n",
      "- Post Created Time:\n",
      "    Unique values : 1\n",
      "    Most frequent : '13:20:50' (1 times)'\n",
      "- Type:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'Photo' (1 times)'\n",
      "- Total Interactions:\n",
      "    Unique values : 1\n",
      "    Most frequent : '1,304' (1 times)'\n",
      "- Video Share Status:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (1 times)'\n",
      "- Is Video Owner?:\n",
      "    Unique values : 1\n",
      "    Most frequent : '-' (1 times)'\n",
      "- Video Length:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (1 times)'\n",
      "- Sponsor Id:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (1 times)'\n",
      "- Sponsor Name:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (1 times)'\n",
      "- Sponsor Category:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (1 times)'\n",
      "- illuminating_scored_messageelection_integrity_Truth_illuminating:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (1 times)'\n",
      "\n",
      "\n",
      "============================================================\n",
      "🔗 Grouped by Facebook_Id = 32fc18da91029ff09bf74fe9887eace6b5d2145809d583f696e344530508b064, post_id = f5463701acdf6caa183d0d4244c7313ef971cc8d2de1b44dfbb4c04badb32025\n",
      "============================================================\n",
      "\n",
      "📊 Numeric Summary:\n",
      "shape: (9, 41)\n",
      "┌────────────┬───────┬──────────┬────────┬───┬─────────────┬─────────────┬────────────┬────────────┐\n",
      "│ statistic  ┆ Likes ┆ Comments ┆ Shares ┆ … ┆ incivility_ ┆ scam_illumi ┆ freefair_i ┆ fraud_illu │\n",
      "│ ---        ┆ ---   ┆ ---      ┆ ---    ┆   ┆ illuminatin ┆ nating      ┆ lluminatin ┆ minating   │\n",
      "│ str        ┆ f64   ┆ f64      ┆ f64    ┆   ┆ g           ┆ ---         ┆ g          ┆ ---        │\n",
      "│            ┆       ┆          ┆        ┆   ┆ ---         ┆ f64         ┆ ---        ┆ f64        │\n",
      "│            ┆       ┆          ┆        ┆   ┆ f64         ┆             ┆ f64        ┆            │\n",
      "╞════════════╪═══════╪══════════╪════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡\n",
      "│ count      ┆ 1.0   ┆ 1.0      ┆ 1.0    ┆ … ┆ 1.0         ┆ 1.0         ┆ 1.0        ┆ 1.0        │\n",
      "│ null_count ┆ 0.0   ┆ 0.0      ┆ 0.0    ┆ … ┆ 0.0         ┆ 0.0         ┆ 0.0        ┆ 0.0        │\n",
      "│ mean       ┆ 30.0  ┆ 2.0      ┆ 1.0    ┆ … ┆ 0.0         ┆ 0.0         ┆ 0.0        ┆ 0.0        │\n",
      "│ std        ┆ null  ┆ null     ┆ null   ┆ … ┆ null        ┆ null        ┆ null       ┆ null       │\n",
      "│ min        ┆ 30.0  ┆ 2.0      ┆ 1.0    ┆ … ┆ 0.0         ┆ 0.0         ┆ 0.0        ┆ 0.0        │\n",
      "│ 25%        ┆ 30.0  ┆ 2.0      ┆ 1.0    ┆ … ┆ 0.0         ┆ 0.0         ┆ 0.0        ┆ 0.0        │\n",
      "│ 50%        ┆ 30.0  ┆ 2.0      ┆ 1.0    ┆ … ┆ 0.0         ┆ 0.0         ┆ 0.0        ┆ 0.0        │\n",
      "│ 75%        ┆ 30.0  ┆ 2.0      ┆ 1.0    ┆ … ┆ 0.0         ┆ 0.0         ┆ 0.0        ┆ 0.0        │\n",
      "│ max        ┆ 30.0  ┆ 2.0      ┆ 1.0    ┆ … ┆ 0.0         ┆ 0.0         ┆ 0.0        ┆ 0.0        │\n",
      "└────────────┴───────┴──────────┴────────┴───┴─────────────┴─────────────┴────────────┴────────────┘\n",
      "\n",
      "📝 Categorical Summary:\n",
      "- Facebook_Id:\n",
      "    Unique values : 1\n",
      "    Most frequent : '32fc18da91029ff09bf74fe9887eace6b5d2145809d583f696e344530508b064' (1 times)'\n",
      "- post_id:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'f5463701acdf6caa183d0d4244c7313ef971cc8d2de1b44dfbb4c04badb32025' (1 times)'\n",
      "- Page Category:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'PERSON' (1 times)'\n",
      "- Page Admin Top Country:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'US' (1 times)'\n",
      "- Post Created:\n",
      "    Unique values : 1\n",
      "    Most frequent : '2024-01-02 12:41:16 EST' (1 times)'\n",
      "- Post Created Date:\n",
      "    Unique values : 1\n",
      "    Most frequent : '2024-01-02' (1 times)'\n",
      "- Post Created Time:\n",
      "    Unique values : 1\n",
      "    Most frequent : '12:41:16' (1 times)'\n",
      "- Type:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'Link' (1 times)'\n",
      "- Total Interactions:\n",
      "    Unique values : 1\n",
      "    Most frequent : '35' (1 times)'\n",
      "- Video Share Status:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (1 times)'\n",
      "- Is Video Owner?:\n",
      "    Unique values : 1\n",
      "    Most frequent : '-' (1 times)'\n",
      "- Video Length:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (1 times)'\n",
      "- Sponsor Id:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (1 times)'\n",
      "- Sponsor Name:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (1 times)'\n",
      "- Sponsor Category:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (1 times)'\n",
      "- illuminating_scored_messageelection_integrity_Truth_illuminating:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (1 times)'\n",
      "\n",
      "\n",
      "============================================================\n",
      "🔗 Grouped by Facebook_Id = 7f5731ac8e6959576e781064b5fa76e059200cdfc3f4e0d7b68bc98792d2cf5b, post_id = aecfe34a0b06bfafd47b92aa2f8196c0640ee296c03d7d4a92cfefb8c61c88b3\n",
      "============================================================\n",
      "\n",
      "📊 Numeric Summary:\n",
      "shape: (9, 41)\n",
      "┌────────────┬───────┬──────────┬────────┬───┬─────────────┬─────────────┬────────────┬────────────┐\n",
      "│ statistic  ┆ Likes ┆ Comments ┆ Shares ┆ … ┆ incivility_ ┆ scam_illumi ┆ freefair_i ┆ fraud_illu │\n",
      "│ ---        ┆ ---   ┆ ---      ┆ ---    ┆   ┆ illuminatin ┆ nating      ┆ lluminatin ┆ minating   │\n",
      "│ str        ┆ f64   ┆ f64      ┆ f64    ┆   ┆ g           ┆ ---         ┆ g          ┆ ---        │\n",
      "│            ┆       ┆          ┆        ┆   ┆ ---         ┆ f64         ┆ ---        ┆ f64        │\n",
      "│            ┆       ┆          ┆        ┆   ┆ f64         ┆             ┆ f64        ┆            │\n",
      "╞════════════╪═══════╪══════════╪════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡\n",
      "│ count      ┆ 1.0   ┆ 1.0      ┆ 1.0    ┆ … ┆ 1.0         ┆ 1.0         ┆ 1.0        ┆ 1.0        │\n",
      "│ null_count ┆ 0.0   ┆ 0.0      ┆ 0.0    ┆ … ┆ 0.0         ┆ 0.0         ┆ 0.0        ┆ 0.0        │\n",
      "│ mean       ┆ 945.0 ┆ 512.0    ┆ 33.0   ┆ … ┆ 0.0         ┆ 0.0         ┆ 0.0        ┆ 0.0        │\n",
      "│ std        ┆ null  ┆ null     ┆ null   ┆ … ┆ null        ┆ null        ┆ null       ┆ null       │\n",
      "│ min        ┆ 945.0 ┆ 512.0    ┆ 33.0   ┆ … ┆ 0.0         ┆ 0.0         ┆ 0.0        ┆ 0.0        │\n",
      "│ 25%        ┆ 945.0 ┆ 512.0    ┆ 33.0   ┆ … ┆ 0.0         ┆ 0.0         ┆ 0.0        ┆ 0.0        │\n",
      "│ 50%        ┆ 945.0 ┆ 512.0    ┆ 33.0   ┆ … ┆ 0.0         ┆ 0.0         ┆ 0.0        ┆ 0.0        │\n",
      "│ 75%        ┆ 945.0 ┆ 512.0    ┆ 33.0   ┆ … ┆ 0.0         ┆ 0.0         ┆ 0.0        ┆ 0.0        │\n",
      "│ max        ┆ 945.0 ┆ 512.0    ┆ 33.0   ┆ … ┆ 0.0         ┆ 0.0         ┆ 0.0        ┆ 0.0        │\n",
      "└────────────┴───────┴──────────┴────────┴───┴─────────────┴─────────────┴────────────┴────────────┘\n",
      "\n",
      "📝 Categorical Summary:\n",
      "- Facebook_Id:\n",
      "    Unique values : 1\n",
      "    Most frequent : '7f5731ac8e6959576e781064b5fa76e059200cdfc3f4e0d7b68bc98792d2cf5b' (1 times)'\n",
      "- post_id:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'aecfe34a0b06bfafd47b92aa2f8196c0640ee296c03d7d4a92cfefb8c61c88b3' (1 times)'\n",
      "- Page Category:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'PERSON' (1 times)'\n",
      "- Page Admin Top Country:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'US' (1 times)'\n",
      "- Post Created:\n",
      "    Unique values : 1\n",
      "    Most frequent : '2024-01-19 09:50:09 EST' (1 times)'\n",
      "- Post Created Date:\n",
      "    Unique values : 1\n",
      "    Most frequent : '2024-01-19' (1 times)'\n",
      "- Post Created Time:\n",
      "    Unique values : 1\n",
      "    Most frequent : '09:50:09' (1 times)'\n",
      "- Type:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'Photo' (1 times)'\n",
      "- Total Interactions:\n",
      "    Unique values : 1\n",
      "    Most frequent : '1,724' (1 times)'\n",
      "- Video Share Status:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (1 times)'\n",
      "- Is Video Owner?:\n",
      "    Unique values : 1\n",
      "    Most frequent : '-' (1 times)'\n",
      "- Video Length:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (1 times)'\n",
      "- Sponsor Id:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (1 times)'\n",
      "- Sponsor Name:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (1 times)'\n",
      "- Sponsor Category:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (1 times)'\n",
      "- illuminating_scored_messageelection_integrity_Truth_illuminating:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (1 times)'\n",
      "\n",
      "\n",
      "============================================================\n",
      "🔗 Grouped by Facebook_Id = 7f5731ac8e6959576e781064b5fa76e059200cdfc3f4e0d7b68bc98792d2cf5b, post_id = f3a918107102a98ab4cd45e7f288120aa9ebcff75d46cdbdf56458882f8c4f86\n",
      "============================================================\n",
      "\n",
      "📊 Numeric Summary:\n",
      "shape: (9, 41)\n",
      "┌────────────┬────────┬──────────┬────────┬───┬─────────────┬────────────┬────────────┬────────────┐\n",
      "│ statistic  ┆ Likes  ┆ Comments ┆ Shares ┆ … ┆ incivility_ ┆ scam_illum ┆ freefair_i ┆ fraud_illu │\n",
      "│ ---        ┆ ---    ┆ ---      ┆ ---    ┆   ┆ illuminatin ┆ inating    ┆ lluminatin ┆ minating   │\n",
      "│ str        ┆ f64    ┆ f64      ┆ f64    ┆   ┆ g           ┆ ---        ┆ g          ┆ ---        │\n",
      "│            ┆        ┆          ┆        ┆   ┆ ---         ┆ f64        ┆ ---        ┆ f64        │\n",
      "│            ┆        ┆          ┆        ┆   ┆ f64         ┆            ┆ f64        ┆            │\n",
      "╞════════════╪════════╪══════════╪════════╪═══╪═════════════╪════════════╪════════════╪════════════╡\n",
      "│ count      ┆ 1.0    ┆ 1.0      ┆ 1.0    ┆ … ┆ 1.0         ┆ 1.0        ┆ 1.0        ┆ 1.0        │\n",
      "│ null_count ┆ 0.0    ┆ 0.0      ┆ 0.0    ┆ … ┆ 0.0         ┆ 0.0        ┆ 0.0        ┆ 0.0        │\n",
      "│ mean       ┆ 1443.0 ┆ 308.0    ┆ 262.0  ┆ … ┆ 0.0         ┆ 0.0        ┆ 0.0        ┆ 0.0        │\n",
      "│ std        ┆ null   ┆ null     ┆ null   ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │\n",
      "│ min        ┆ 1443.0 ┆ 308.0    ┆ 262.0  ┆ … ┆ 0.0         ┆ 0.0        ┆ 0.0        ┆ 0.0        │\n",
      "│ 25%        ┆ 1443.0 ┆ 308.0    ┆ 262.0  ┆ … ┆ 0.0         ┆ 0.0        ┆ 0.0        ┆ 0.0        │\n",
      "│ 50%        ┆ 1443.0 ┆ 308.0    ┆ 262.0  ┆ … ┆ 0.0         ┆ 0.0        ┆ 0.0        ┆ 0.0        │\n",
      "│ 75%        ┆ 1443.0 ┆ 308.0    ┆ 262.0  ┆ … ┆ 0.0         ┆ 0.0        ┆ 0.0        ┆ 0.0        │\n",
      "│ max        ┆ 1443.0 ┆ 308.0    ┆ 262.0  ┆ … ┆ 0.0         ┆ 0.0        ┆ 0.0        ┆ 0.0        │\n",
      "└────────────┴────────┴──────────┴────────┴───┴─────────────┴────────────┴────────────┴────────────┘\n",
      "\n",
      "📝 Categorical Summary:\n",
      "- Facebook_Id:\n",
      "    Unique values : 1\n",
      "    Most frequent : '7f5731ac8e6959576e781064b5fa76e059200cdfc3f4e0d7b68bc98792d2cf5b' (1 times)'\n",
      "- post_id:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'f3a918107102a98ab4cd45e7f288120aa9ebcff75d46cdbdf56458882f8c4f86' (1 times)'\n",
      "- Page Category:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'PERSON' (1 times)'\n",
      "- Page Admin Top Country:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'US' (1 times)'\n",
      "- Post Created:\n",
      "    Unique values : 1\n",
      "    Most frequent : '2023-09-02 08:45:01 EDT' (1 times)'\n",
      "- Post Created Date:\n",
      "    Unique values : 1\n",
      "    Most frequent : '2023-09-02' (1 times)'\n",
      "- Post Created Time:\n",
      "    Unique values : 1\n",
      "    Most frequent : '08:45:01' (1 times)'\n",
      "- Type:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'Photo' (1 times)'\n",
      "- Total Interactions:\n",
      "    Unique values : 1\n",
      "    Most frequent : '2,393' (1 times)'\n",
      "- Video Share Status:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (1 times)'\n",
      "- Is Video Owner?:\n",
      "    Unique values : 1\n",
      "    Most frequent : '-' (1 times)'\n",
      "- Video Length:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (1 times)'\n",
      "- Sponsor Id:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (1 times)'\n",
      "- Sponsor Name:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (1 times)'\n",
      "- Sponsor Category:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (1 times)'\n",
      "- illuminating_scored_messageelection_integrity_Truth_illuminating:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (1 times)'\n",
      "\n",
      "\n",
      "============================================================\n",
      "🔗 Grouped by Facebook_Id = 32fc18da91029ff09bf74fe9887eace6b5d2145809d583f696e344530508b064, post_id = 65021af396fb17e9308e9961613d5bd25becdc8a712abfdefca702a027c6e77a\n",
      "============================================================\n",
      "\n",
      "📊 Numeric Summary:\n",
      "shape: (9, 41)\n",
      "┌────────────┬───────┬──────────┬────────┬───┬─────────────┬─────────────┬────────────┬────────────┐\n",
      "│ statistic  ┆ Likes ┆ Comments ┆ Shares ┆ … ┆ incivility_ ┆ scam_illumi ┆ freefair_i ┆ fraud_illu │\n",
      "│ ---        ┆ ---   ┆ ---      ┆ ---    ┆   ┆ illuminatin ┆ nating      ┆ lluminatin ┆ minating   │\n",
      "│ str        ┆ f64   ┆ f64      ┆ f64    ┆   ┆ g           ┆ ---         ┆ g          ┆ ---        │\n",
      "│            ┆       ┆          ┆        ┆   ┆ ---         ┆ f64         ┆ ---        ┆ f64        │\n",
      "│            ┆       ┆          ┆        ┆   ┆ f64         ┆             ┆ f64        ┆            │\n",
      "╞════════════╪═══════╪══════════╪════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡\n",
      "│ count      ┆ 1.0   ┆ 1.0      ┆ 1.0    ┆ … ┆ 1.0         ┆ 1.0         ┆ 1.0        ┆ 1.0        │\n",
      "│ null_count ┆ 0.0   ┆ 0.0      ┆ 0.0    ┆ … ┆ 0.0         ┆ 0.0         ┆ 0.0        ┆ 0.0        │\n",
      "│ mean       ┆ 11.0  ┆ 3.0      ┆ 0.0    ┆ … ┆ 0.0         ┆ 0.0         ┆ 0.0        ┆ 0.0        │\n",
      "│ std        ┆ null  ┆ null     ┆ null   ┆ … ┆ null        ┆ null        ┆ null       ┆ null       │\n",
      "│ min        ┆ 11.0  ┆ 3.0      ┆ 0.0    ┆ … ┆ 0.0         ┆ 0.0         ┆ 0.0        ┆ 0.0        │\n",
      "│ 25%        ┆ 11.0  ┆ 3.0      ┆ 0.0    ┆ … ┆ 0.0         ┆ 0.0         ┆ 0.0        ┆ 0.0        │\n",
      "│ 50%        ┆ 11.0  ┆ 3.0      ┆ 0.0    ┆ … ┆ 0.0         ┆ 0.0         ┆ 0.0        ┆ 0.0        │\n",
      "│ 75%        ┆ 11.0  ┆ 3.0      ┆ 0.0    ┆ … ┆ 0.0         ┆ 0.0         ┆ 0.0        ┆ 0.0        │\n",
      "│ max        ┆ 11.0  ┆ 3.0      ┆ 0.0    ┆ … ┆ 0.0         ┆ 0.0         ┆ 0.0        ┆ 0.0        │\n",
      "└────────────┴───────┴──────────┴────────┴───┴─────────────┴─────────────┴────────────┴────────────┘\n",
      "\n",
      "📝 Categorical Summary:\n",
      "- Facebook_Id:\n",
      "    Unique values : 1\n",
      "    Most frequent : '32fc18da91029ff09bf74fe9887eace6b5d2145809d583f696e344530508b064' (1 times)'\n",
      "- post_id:\n",
      "    Unique values : 1\n",
      "    Most frequent : '65021af396fb17e9308e9961613d5bd25becdc8a712abfdefca702a027c6e77a' (1 times)'\n",
      "- Page Category:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'ACTOR' (1 times)'\n",
      "- Page Admin Top Country:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'US' (1 times)'\n",
      "- Post Created:\n",
      "    Unique values : 1\n",
      "    Most frequent : '2024-05-15 10:26:22 EDT' (1 times)'\n",
      "- Post Created Date:\n",
      "    Unique values : 1\n",
      "    Most frequent : '2024-05-15' (1 times)'\n",
      "- Post Created Time:\n",
      "    Unique values : 1\n",
      "    Most frequent : '10:26:22' (1 times)'\n",
      "- Type:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'Link' (1 times)'\n",
      "- Total Interactions:\n",
      "    Unique values : 1\n",
      "    Most frequent : '18' (1 times)'\n",
      "- Video Share Status:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (1 times)'\n",
      "- Is Video Owner?:\n",
      "    Unique values : 1\n",
      "    Most frequent : '-' (1 times)'\n",
      "- Video Length:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (1 times)'\n",
      "- Sponsor Id:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (1 times)'\n",
      "- Sponsor Name:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (1 times)'\n",
      "- Sponsor Category:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (1 times)'\n",
      "- illuminating_scored_messageelection_integrity_Truth_illuminating:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (1 times)'\n",
      "\n",
      "\n",
      "============================================================\n",
      "🔗 Grouped by Facebook_Id = 32fc18da91029ff09bf74fe9887eace6b5d2145809d583f696e344530508b064, post_id = 786373b2f30cc9c88230bb6a5d5c0b569833ac66f5615be547c081eecc0bc65d\n",
      "============================================================\n",
      "\n",
      "📊 Numeric Summary:\n",
      "shape: (9, 41)\n",
      "┌────────────┬───────┬──────────┬────────┬───┬─────────────┬─────────────┬────────────┬────────────┐\n",
      "│ statistic  ┆ Likes ┆ Comments ┆ Shares ┆ … ┆ incivility_ ┆ scam_illumi ┆ freefair_i ┆ fraud_illu │\n",
      "│ ---        ┆ ---   ┆ ---      ┆ ---    ┆   ┆ illuminatin ┆ nating      ┆ lluminatin ┆ minating   │\n",
      "│ str        ┆ f64   ┆ f64      ┆ f64    ┆   ┆ g           ┆ ---         ┆ g          ┆ ---        │\n",
      "│            ┆       ┆          ┆        ┆   ┆ ---         ┆ f64         ┆ ---        ┆ f64        │\n",
      "│            ┆       ┆          ┆        ┆   ┆ f64         ┆             ┆ f64        ┆            │\n",
      "╞════════════╪═══════╪══════════╪════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡\n",
      "│ count      ┆ 1.0   ┆ 1.0      ┆ 1.0    ┆ … ┆ 1.0         ┆ 1.0         ┆ 1.0        ┆ 1.0        │\n",
      "│ null_count ┆ 0.0   ┆ 0.0      ┆ 0.0    ┆ … ┆ 0.0         ┆ 0.0         ┆ 0.0        ┆ 0.0        │\n",
      "│ mean       ┆ 90.0  ┆ 78.0     ┆ 9.0    ┆ … ┆ 0.0         ┆ 0.0         ┆ 0.0        ┆ 0.0        │\n",
      "│ std        ┆ null  ┆ null     ┆ null   ┆ … ┆ null        ┆ null        ┆ null       ┆ null       │\n",
      "│ min        ┆ 90.0  ┆ 78.0     ┆ 9.0    ┆ … ┆ 0.0         ┆ 0.0         ┆ 0.0        ┆ 0.0        │\n",
      "│ 25%        ┆ 90.0  ┆ 78.0     ┆ 9.0    ┆ … ┆ 0.0         ┆ 0.0         ┆ 0.0        ┆ 0.0        │\n",
      "│ 50%        ┆ 90.0  ┆ 78.0     ┆ 9.0    ┆ … ┆ 0.0         ┆ 0.0         ┆ 0.0        ┆ 0.0        │\n",
      "│ 75%        ┆ 90.0  ┆ 78.0     ┆ 9.0    ┆ … ┆ 0.0         ┆ 0.0         ┆ 0.0        ┆ 0.0        │\n",
      "│ max        ┆ 90.0  ┆ 78.0     ┆ 9.0    ┆ … ┆ 0.0         ┆ 0.0         ┆ 0.0        ┆ 0.0        │\n",
      "└────────────┴───────┴──────────┴────────┴───┴─────────────┴─────────────┴────────────┴────────────┘\n",
      "\n",
      "📝 Categorical Summary:\n",
      "- Facebook_Id:\n",
      "    Unique values : 1\n",
      "    Most frequent : '32fc18da91029ff09bf74fe9887eace6b5d2145809d583f696e344530508b064' (1 times)'\n",
      "- post_id:\n",
      "    Unique values : 1\n",
      "    Most frequent : '786373b2f30cc9c88230bb6a5d5c0b569833ac66f5615be547c081eecc0bc65d' (1 times)'\n",
      "- Page Category:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'ACTOR' (1 times)'\n",
      "- Page Admin Top Country:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'US' (1 times)'\n",
      "- Post Created:\n",
      "    Unique values : 1\n",
      "    Most frequent : '2024-07-25 03:26:39 EDT' (1 times)'\n",
      "- Post Created Date:\n",
      "    Unique values : 1\n",
      "    Most frequent : '2024-07-25' (1 times)'\n",
      "- Post Created Time:\n",
      "    Unique values : 1\n",
      "    Most frequent : '03:26:39' (1 times)'\n",
      "- Type:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'YouTube' (1 times)'\n",
      "- Total Interactions:\n",
      "    Unique values : 1\n",
      "    Most frequent : '212' (1 times)'\n",
      "- Video Share Status:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (1 times)'\n",
      "- Is Video Owner?:\n",
      "    Unique values : 1\n",
      "    Most frequent : '-' (1 times)'\n",
      "- Video Length:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (1 times)'\n",
      "- Sponsor Id:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (1 times)'\n",
      "- Sponsor Name:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (1 times)'\n",
      "- Sponsor Category:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (1 times)'\n",
      "- illuminating_scored_messageelection_integrity_Truth_illuminating:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (1 times)'\n",
      "\n",
      "\n",
      "============================================================\n",
      "🔗 Grouped by Facebook_Id = 8e8dac0ee6f22255b9d9365845a7fb830627cc27d34934c4f097689ec8da6719, post_id = 92bf7bd1f92e80f4005877d72f2ffb7c6e12290350f96e05e1f75fca39bdfb5c\n",
      "============================================================\n",
      "\n",
      "📊 Numeric Summary:\n",
      "shape: (9, 41)\n",
      "┌────────────┬────────┬──────────┬────────┬───┬─────────────┬────────────┬────────────┬────────────┐\n",
      "│ statistic  ┆ Likes  ┆ Comments ┆ Shares ┆ … ┆ incivility_ ┆ scam_illum ┆ freefair_i ┆ fraud_illu │\n",
      "│ ---        ┆ ---    ┆ ---      ┆ ---    ┆   ┆ illuminatin ┆ inating    ┆ lluminatin ┆ minating   │\n",
      "│ str        ┆ f64    ┆ f64      ┆ f64    ┆   ┆ g           ┆ ---        ┆ g          ┆ ---        │\n",
      "│            ┆        ┆          ┆        ┆   ┆ ---         ┆ f64        ┆ ---        ┆ f64        │\n",
      "│            ┆        ┆          ┆        ┆   ┆ f64         ┆            ┆ f64        ┆            │\n",
      "╞════════════╪════════╪══════════╪════════╪═══╪═════════════╪════════════╪════════════╪════════════╡\n",
      "│ count      ┆ 1.0    ┆ 1.0      ┆ 1.0    ┆ … ┆ 1.0         ┆ 1.0        ┆ 1.0        ┆ 1.0        │\n",
      "│ null_count ┆ 0.0    ┆ 0.0      ┆ 0.0    ┆ … ┆ 0.0         ┆ 0.0        ┆ 0.0        ┆ 0.0        │\n",
      "│ mean       ┆ 1074.0 ┆ 247.0    ┆ 12.0   ┆ … ┆ 0.0         ┆ 0.0        ┆ 0.0        ┆ 0.0        │\n",
      "│ std        ┆ null   ┆ null     ┆ null   ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │\n",
      "│ min        ┆ 1074.0 ┆ 247.0    ┆ 12.0   ┆ … ┆ 0.0         ┆ 0.0        ┆ 0.0        ┆ 0.0        │\n",
      "│ 25%        ┆ 1074.0 ┆ 247.0    ┆ 12.0   ┆ … ┆ 0.0         ┆ 0.0        ┆ 0.0        ┆ 0.0        │\n",
      "│ 50%        ┆ 1074.0 ┆ 247.0    ┆ 12.0   ┆ … ┆ 0.0         ┆ 0.0        ┆ 0.0        ┆ 0.0        │\n",
      "│ 75%        ┆ 1074.0 ┆ 247.0    ┆ 12.0   ┆ … ┆ 0.0         ┆ 0.0        ┆ 0.0        ┆ 0.0        │\n",
      "│ max        ┆ 1074.0 ┆ 247.0    ┆ 12.0   ┆ … ┆ 0.0         ┆ 0.0        ┆ 0.0        ┆ 0.0        │\n",
      "└────────────┴────────┴──────────┴────────┴───┴─────────────┴────────────┴────────────┴────────────┘\n",
      "\n",
      "📝 Categorical Summary:\n",
      "- Facebook_Id:\n",
      "    Unique values : 1\n",
      "    Most frequent : '8e8dac0ee6f22255b9d9365845a7fb830627cc27d34934c4f097689ec8da6719' (1 times)'\n",
      "- post_id:\n",
      "    Unique values : 1\n",
      "    Most frequent : '92bf7bd1f92e80f4005877d72f2ffb7c6e12290350f96e05e1f75fca39bdfb5c' (1 times)'\n",
      "- Page Category:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'POLITICIAN' (1 times)'\n",
      "- Page Admin Top Country:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'US' (1 times)'\n",
      "- Post Created:\n",
      "    Unique values : 1\n",
      "    Most frequent : '2023-12-26 17:49:06 EST' (1 times)'\n",
      "- Post Created Date:\n",
      "    Unique values : 1\n",
      "    Most frequent : '2023-12-26' (1 times)'\n",
      "- Post Created Time:\n",
      "    Unique values : 1\n",
      "    Most frequent : '17:49:06' (1 times)'\n",
      "- Type:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'Status' (1 times)'\n",
      "- Total Interactions:\n",
      "    Unique values : 1\n",
      "    Most frequent : '1,600' (1 times)'\n",
      "- Video Share Status:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (1 times)'\n",
      "- Is Video Owner?:\n",
      "    Unique values : 1\n",
      "    Most frequent : '-' (1 times)'\n",
      "- Video Length:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (1 times)'\n",
      "- Sponsor Id:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (1 times)'\n",
      "- Sponsor Name:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (1 times)'\n",
      "- Sponsor Category:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (1 times)'\n",
      "- illuminating_scored_messageelection_integrity_Truth_illuminating:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (1 times)'\n",
      "\n",
      "\n",
      "============================================================\n",
      "🔗 Grouped by Facebook_Id = 7f5731ac8e6959576e781064b5fa76e059200cdfc3f4e0d7b68bc98792d2cf5b, post_id = 6754d5fbaab66ca4758efbeeafd1b94b1415d7be2d77010312d32ea08523b81d\n",
      "============================================================\n",
      "\n",
      "📊 Numeric Summary:\n",
      "shape: (9, 41)\n",
      "┌────────────┬───────┬──────────┬────────┬───┬─────────────┬─────────────┬────────────┬────────────┐\n",
      "│ statistic  ┆ Likes ┆ Comments ┆ Shares ┆ … ┆ incivility_ ┆ scam_illumi ┆ freefair_i ┆ fraud_illu │\n",
      "│ ---        ┆ ---   ┆ ---      ┆ ---    ┆   ┆ illuminatin ┆ nating      ┆ lluminatin ┆ minating   │\n",
      "│ str        ┆ f64   ┆ f64      ┆ f64    ┆   ┆ g           ┆ ---         ┆ g          ┆ ---        │\n",
      "│            ┆       ┆          ┆        ┆   ┆ ---         ┆ f64         ┆ ---        ┆ f64        │\n",
      "│            ┆       ┆          ┆        ┆   ┆ f64         ┆             ┆ f64        ┆            │\n",
      "╞════════════╪═══════╪══════════╪════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡\n",
      "│ count      ┆ 1.0   ┆ 1.0      ┆ 1.0    ┆ … ┆ 1.0         ┆ 1.0         ┆ 1.0        ┆ 1.0        │\n",
      "│ null_count ┆ 0.0   ┆ 0.0      ┆ 0.0    ┆ … ┆ 0.0         ┆ 0.0         ┆ 0.0        ┆ 0.0        │\n",
      "│ mean       ┆ 916.0 ┆ 738.0    ┆ 86.0   ┆ … ┆ 0.0         ┆ 0.0         ┆ 0.0        ┆ 0.0        │\n",
      "│ std        ┆ null  ┆ null     ┆ null   ┆ … ┆ null        ┆ null        ┆ null       ┆ null       │\n",
      "│ min        ┆ 916.0 ┆ 738.0    ┆ 86.0   ┆ … ┆ 0.0         ┆ 0.0         ┆ 0.0        ┆ 0.0        │\n",
      "│ 25%        ┆ 916.0 ┆ 738.0    ┆ 86.0   ┆ … ┆ 0.0         ┆ 0.0         ┆ 0.0        ┆ 0.0        │\n",
      "│ 50%        ┆ 916.0 ┆ 738.0    ┆ 86.0   ┆ … ┆ 0.0         ┆ 0.0         ┆ 0.0        ┆ 0.0        │\n",
      "│ 75%        ┆ 916.0 ┆ 738.0    ┆ 86.0   ┆ … ┆ 0.0         ┆ 0.0         ┆ 0.0        ┆ 0.0        │\n",
      "│ max        ┆ 916.0 ┆ 738.0    ┆ 86.0   ┆ … ┆ 0.0         ┆ 0.0         ┆ 0.0        ┆ 0.0        │\n",
      "└────────────┴───────┴──────────┴────────┴───┴─────────────┴─────────────┴────────────┴────────────┘\n",
      "\n",
      "📝 Categorical Summary:\n",
      "- Facebook_Id:\n",
      "    Unique values : 1\n",
      "    Most frequent : '7f5731ac8e6959576e781064b5fa76e059200cdfc3f4e0d7b68bc98792d2cf5b' (1 times)'\n",
      "- post_id:\n",
      "    Unique values : 1\n",
      "    Most frequent : '6754d5fbaab66ca4758efbeeafd1b94b1415d7be2d77010312d32ea08523b81d' (1 times)'\n",
      "- Page Category:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'PERSON' (1 times)'\n",
      "- Page Admin Top Country:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'US' (1 times)'\n",
      "- Post Created:\n",
      "    Unique values : 1\n",
      "    Most frequent : '2024-07-30 12:02:19 EDT' (1 times)'\n",
      "- Post Created Date:\n",
      "    Unique values : 1\n",
      "    Most frequent : '2024-07-30' (1 times)'\n",
      "- Post Created Time:\n",
      "    Unique values : 1\n",
      "    Most frequent : '12:02:19' (1 times)'\n",
      "- Type:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'Photo' (1 times)'\n",
      "- Total Interactions:\n",
      "    Unique values : 1\n",
      "    Most frequent : '1,842' (1 times)'\n",
      "- Video Share Status:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (1 times)'\n",
      "- Is Video Owner?:\n",
      "    Unique values : 1\n",
      "    Most frequent : '-' (1 times)'\n",
      "- Video Length:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (1 times)'\n",
      "- Sponsor Id:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (1 times)'\n",
      "- Sponsor Name:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (1 times)'\n",
      "- Sponsor Category:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (1 times)'\n",
      "- illuminating_scored_messageelection_integrity_Truth_illuminating:\n",
      "    Unique values : 1\n",
      "    Most frequent : 'None' (1 times)'\n",
      "\n"
     ]
    }
   ],
   "source": [
    "import polars as pl\n",
    "\n",
    "DATA_FILE = \"2024_fb_posts_president_scored_anon.csv\"\n",
    "\n",
    "# Load and deduplicate columns\n",
    "df = pl.read_csv(DATA_FILE)\n",
    "df = df.select([pl.col(c) for i, c in enumerate(df.columns) if c not in df.columns[:i]])\n",
    "\n",
    "# Determine column types\n",
    "numeric_cols = [col for col in df.columns if df[col].dtype in (pl.Float64, pl.Int64)]\n",
    "non_numeric_cols = [col for col in df.columns if df[col].dtype == pl.Utf8]\n",
    "\n",
    "# === Summary Printer ===\n",
    "def summarize(df_part: pl.DataFrame, label: str):\n",
    "    print(f\"\\n{'=' * 60}\\n{label}\\n{'=' * 60}\")\n",
    "\n",
    "    if df_part.is_empty():\n",
    "        print(\"No data available.\\n\")\n",
    "        return\n",
    "\n",
    "    if numeric_cols:\n",
    "        print(\"\\n📊 Numeric Summary:\")\n",
    "        numeric_data = df_part.select([pl.col(col).cast(pl.Float64) for col in numeric_cols])\n",
    "        print(numeric_data.describe())\n",
    "\n",
    "    print(\"\\n📝 Categorical Summary:\")\n",
    "    for col in non_numeric_cols:\n",
    "        unique_vals = df_part.select(pl.col(col).n_unique()).item()\n",
    "        vc = df_part.select(pl.col(col).value_counts()).unnest(col)\n",
    "        if vc.height > 0:\n",
    "            most_common = vc[0, col]\n",
    "            most_count = vc[0, \"count\"]\n",
    "            print(f\"- {col}:\")\n",
    "            print(f\"    Unique values : {unique_vals}\")\n",
    "            print(f\"    Most frequent : '{most_common}' ({most_count} times)'\")\n",
    "    print()\n",
    "\n",
    "# === Overall Summary ===\n",
    "summarize(df, \"🌐 Overall Facebook Posts Summary\")\n",
    "\n",
    "# === Grouped by Facebook_Id (first 5)\n",
    "if \"Facebook_Id\" in df.columns:\n",
    "    unique_ids = df.select(\"Facebook_Id\").unique().head(5)[\"Facebook_Id\"]\n",
    "    for fb_id in unique_ids:\n",
    "        group_df = df.filter(pl.col(\"Facebook_Id\") == fb_id)\n",
    "        summarize(group_df, f\"📁 Grouped by Facebook_Id = {fb_id}\")\n",
    "\n",
    "# === Grouped by Facebook_Id + post_id (top 10 combos)\n",
    "if all(col in df.columns for col in [\"Facebook_Id\", \"post_id\"]):\n",
    "    top_10 = (\n",
    "        df.group_by([\"Facebook_Id\", \"post_id\"])\n",
    "        .agg(pl.len().alias(\"count\"))\n",
    "        .sort(\"count\", descending=True)\n",
    "        .head(10)\n",
    "    )\n",
    "\n",
    "    for row in top_10.iter_rows():\n",
    "        fb_id, post_id, _ = row\n",
    "        group_df = df.filter((pl.col(\"Facebook_Id\") == fb_id) & (pl.col(\"post_id\") == post_id))\n",
    "        summarize(group_df, f\"🔗 Grouped by Facebook_Id = {fb_id}, post_id = {post_id}\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
